spring:
  flyway:
    schemas: HR
    default-schema: HR
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    user: system
    password: hr
    url: jdbc:oracle:thin:@//localhost:1521/orcl
  messages:
    basename: i18n/messages
  application:
    name: task3UserPosts
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/orcl
    username: system
    password: hr
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 6060
logging:
  level:
    org.flywaydb.core: DEBUG
token:
  secret: 829ryhwffh31f3iufhjw98rpur38n43u9
  time: 24h