spring:
  messages:
    basename: i18n/messages
  application:
    name: task3UserPosts
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/orcl
    username: system
    password: hr
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 6060